csharp_proj/Models/Listing.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace csharp_proj.Models;

public class Listing
{
    // === Fields ===
    [Key]
    public int ListingId { get; set; }

    [Required(ErrorMessage = "is required.")]
    [Display(Name = "Title")]
    public string Title { get; set; }

    [Required(ErrorMessage = "is required.")]
    [Display(Name = "Description")]
    public string Description { get; set; }

    [Required(ErrorMessage = "is required.")]
    [DataType(DataType.Currency)]
    [Display(Name = "Price")]
    public double Price { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    // === Field Relationships ===
    public int UserId { get; set; }
    public User? User { get; set; }
}

csharp_proj/Models/Post.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace csharp_proj.Models;

public class Post
{
    // === Fields ===
    [Key]
    public int PostId { get; set; }

    [Required(ErrorMessage = "is required.")]
    [Display(Name = "Subject")]
    public string Subject { get; set; }

    [Required(ErrorMessage = "is required.")]
    [Display(Name = "Message")]
    public string Message { get; set; }

    // TODO: add field for Tags

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    // === Field Relationships ===
    public int UserId { get; set; }
    public User? User { get; set; }
    public List<Comment> Comments { get; set; } = new List<Comment>();
}

csharp_proj/Models/Review.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace csharp_proj.Models;

public class Review
{
    // === Fields ===
    [Key]
    public int ReviewId { get; set; }

    // TODO: eventId from api

    [Required(ErrorMessage = "is required.")]
    [Display(Name = "Rating")]
    public int Rating { get; set; }

    [Required(ErrorMessage = "is required.")]
    [Display(Name = "Description")]
    public string Description { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    // === Field Relationships ===
    public int UserId { get; set; }
    public User? User { get; set; }
}

csharp_proj/Controllers/ListingsController.cs
using csharp_proj.Models;
using Microsoft.AspNetCore.Mvc;
namespace csharp_proj.Controllers;

public class ListingsController : Controller
{
    private MyContext Database; // Instantiate database

    public ListingsController(MyContext database)
    {
        Database = database;
    }

    private int? userId // Checks if user logged in
    {
        get
        {
            return HttpContext.Session.GetInt32("UserId");
        }
    }

    private bool loggedIn
    {
        get
        {
            return userId != null;
        }
    }

    [HttpGet("/listings/new")] // Route: New Listing Form
    public IActionResult NewListing()
    {
        if(!loggedIn)
        {
            return RedirectToAction("Index", "Users");
        }
        return View("NewListing");
    }

    [HttpPost("/listings/create")] // Route: Create Listing
    public IActionResult Create(Listing newListing)
    {
        if(!ModelState.IsValid) // Validate form data
        {
            return NewListing();
        }

        newListing.UserId = (int)userId; // Assign user Id
        Database.Add(newListing); // Add to db
        Database.SaveChanges(); // Save changes
        return RedirectToAction("Share", "Users"); // Redirect to Share page
    }
}

csharp_proj/Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using csharp_proj.Models;
using Microsoft.EntityFrameworkCore;
namespace csharp_proj.Controllers;

public class PostsController : Controller
{
    private MyContext Database; // Instantiate database

    public PostsController(MyContext database)
    {
        Database = database;
    }

    private int? userId // Checks if user logged in
    {
        get
        {
            return HttpContext.Session.GetInt32("UserId");
        }
    }

    private bool loggedIn
    {
        get
        {
            return userId != null;
        }
    }

    [HttpGet("/posts/new")] // Route: New Post Form
    public IActionResult NewPost()
    {
        if(!loggedIn) // Check if user logged in
        {
            return RedirectToAction("Index", "Users");
        }

        return View("NewPost");
    }


    [HttpPost("/posts/create")] // Route: Create Post
    public IActionResult Create(Post newPost)
    {
        if(!ModelState.IsValid) // Validate form data
        {
            return NewPost();
        }

        newPost.UserId = (int)userId; // Attach user ID to post
        Database.Add(newPost); // Add to db
        Database.SaveChanges(); // Save changes
        return RedirectToAction("Share", "Users"); // Redirect to Share page
    }
}

csharp_proj/Controllers/ReviewsController.cs
using csharp_proj.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace csharp_proj.Controllers;

public class ReviewsController : Controller
{
    private MyContext Database; // Instantiate database

    public ReviewsController(MyContext database)
    {
        Database = database;
    }

    private int? userId // Checks if user logged in
    {
        get
        {
            return HttpContext.Session.GetInt32("UserId");
        }
    }

    private bool loggedIn
    {
        get
        {
            return userId != null;
        }
    }

    [HttpGet("/reviews/new")] // Route: New Review Form
    public IActionResult NewReview()
    {
        if(!loggedIn)
        {
            return RedirectToAction("Index", "Users");
        }

        return View("NewReview");
    }

    [HttpPost("/reviews/create")] // Route: Create Review
    public IActionResult Create(Review newReview)
    {
        // Validate form data
        if(!ModelState.IsValid)
        {
            return NewReview();
        }

        newReview.UserId = (int)userId; // Attach user Id to
        Database.Add(newReview); // Add to db
        Database.SaveChanges(); // Save changes
        return RedirectToAction("Share", "Users"); // Redirect to Share page
    }
}

csharp_proj/Views/Shared/NewListing.cshtml
@model Listing

<form class="form-group d-flex justify-content-between m-5" asp-controller="Listings" asp-action="Create" method="post">
    <div class="d-flex flex-column justify-content-between mx-2 ">
    <h1 class="text-center">Create New Listing</h1>
    <hr>
        <label asp-for="Title">Title</label>
        <input asp-for="Title">
        <span asp-validation-for="Title" class="text-danger"></span>
        <br>
        <label asp-for="Description">Description</label>
        <input asp-for="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
        <br>
        <label asp-for="Price">Price</label>
        <input asp-for="Price">
        <span asp-validation-for="Price" class="text-danger"></span>
        <button class="btn btn-secondary mt-3" type="submit">Submit Listing</button>
    </div>
</form>

csharp_proj/Views/Shared/NewPost.cshtml
@model Post

<form class="form-group d-flex justify-content-between m-5" asp-controller="Posts" asp-action="Create" method="post">
    <div class="d-flex flex-column justify-content-between mx-2 ">
    <h1 class="text-center">Create New Post</h1>
    <hr>
        <label asp-for="Subject">Subject</label>
        <input asp-for="Subject">
        <span class="text-danger" asp-validation-for="Subject"></span>
        <br>
        <label asp-for="Message">Message</label>
        <input asp-for="Message">
        <span class="text-danger" asp-validation-for="Message"></span>
        <br>
        <button class="btn btn-secondary mt-3" type="submit">Submit Listing</button>
    </div>
</form>

csharp_proj/Views/Shared/NewReview.cshtml
@model Review

<form class="form-group d-flex justify-content-between m-5" asp-controller="Reviews" asp-action="Create" method="post">
    <div class="d-flex flex-column justify-content-between mx-2 ">
    <h1 class="text-center">Create New Review</h1>
    <hr>
        @* TODO: Add event title *@
        <br>
        <label asp-for="Rating">Rating</label>
        <select asp-for="Rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
        <span asp-validation-for="Rating" class="text-danger"></span>
        <br>
        <label asp-for="Description">Description</label>
        <input asp-for="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
        <button class="btn btn-secondary mt-3" type="submit">Submit Listing</button>
    </div>
</form>

csharp_proj/Views/Shared/SearchEvents.cshtml
<div class="input-group">
    <div class="form-outline flex-fill">
    <input type="search" id="form1" class="form-control form-control-lg" />
    <label class="form-label" for="form1">Search events</label>
    </div>
    <button type="button" class="btn btn-primary">
    <i class="fas fa-search"></i>
    </button>
</div>

</div>
    TODO: Display search results
</div>

csharp_proj/Views/Shared/_Events.cshtml
@{
    ViewData["Rating"] = "Home Page";
}
@model Review;


<div class="container text-center px-2">
    <h1 class="display-4"></h1>
    <div class="mt-5">
        <hr width="100%"/><br/>
        <table class="card bg-light">
            <thead>
                <tr class="d-flex justify-content-around">
                    <td class="w-33">Review</td>
                </tr>
            </thead>
            @* @foreach(Review Review in ViewBag.Wed){ *@
                @* bool Commented = Review.ReviewCommented.Any(g => g.ReviewId == Context.Session.GetInt32("UUID")); *@

                @* <tr class="d-flex justify-content-around">
                    <td class="w-25"><a asp-action="One" asp-controller="Reviews" asp-route-ReviewId="@Review.ReviewId">@Review.Rating</a></td>
                    <td class="bg-secondary w-25">@Review.Description</td> *@
                    @* Maybe include a date for the post???When the concert will occur? *@
                    @* <td class="bg-secondary w-25">@Review.CreatedAt</td> *@
                    @* <td class="w-25">@Review.ReviewCommented.Count()</td> *@


                    @* @if(Context.Session.GetInt32("UUID") == Review.ReviewId){
                        <td class="bg-secondary w-25"><a asp-action="DeleteReview" asp-controller="Reviews" asp-route-ReviewId="@Review.ReviewId">Delete</a></td>
                    } *@
                    @* <form asp-action="Comment" asp-controller="Reviews" asp-route-ReviewId="@Review.ReviewId" method="post">
                        @if(Context.Session.GetInt32("UUID") != Review.ReviewId){
                            @if(!Commented){
                                <td class="bg-secondary w-25"><button type="submit" class="btn-link">Comment</button></td>
                            }
                        }
                    </form> *@
                @* </tr> *@
            }
        </table>

    </div>
</div>

csharp_proj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - csharp_proj</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/csharp_proj.styles.css" asp-append-version="true" />
</head>
<body class="dark">
    <div class="container">
        <div>
            <div class="form-check form-switch">
                <!-- Rounded switch -->
                <label class="switch mt-4" for="checkbox">
                    <input type="checkbox" class="form-check-input" id="checkbox" onclick="setDarkMode()">
                    <span class="slider round"></span>
                </label>
                <button class="theme-toggle-button mt-4" > @* swapper *@
                <svg class="pumpkin" style="width:24px;height:24px" viewBox="0 0 24 24">
                <path fill="currentColor" d="M6.5,6C7.47,6 8.37,6.5 9.11,7.38C9.66,6.79 10.31,6.36 11,6.15V4A2,2 0 0,1 13,2H15V4H13V6.15C13.69,6.36 14.34,6.79 14.89,7.38C15.63,6.5 16.53,6 17.5,6C20,6 22,9.36 22,13.5C22,17.64 20,21 17.5,21C16.53,21 15.63,20.5 14.89,19.62C14.08,20.5 13.08,21 12,21C10.92,21 9.92,20.5 9.11,19.62C8.37,20.5 7.47,21 6.5,21C4,21 2,17.64 2,13.5C2,9.36 4,6 6.5,6M9,10L7.75,12.25H10.25L9,10M15,10L13.75,12.25H16.25L15,10M8,17H10L11,16L12,17H14L15,16L16,17L17.5,14L13.92,14.62L13,16L12,15H10L9,16L8,15L6,14L8,17Z" />
                </svg>
                    Light/Dark Mode
                <svg class="moon" style="width:24px;height:24px" viewBox="0 0 24 24">
                <path fill="currentColor" d="M17.75,4.09L15.22,6.03L16.13,9.09L13.5,7.28L10.87,9.09L11.78,6.03L9.25,4.09L12.44,4L13.5,1L14.56,4L17.75,4.09M21.25,11L19.61,12.25L20.2,14.23L18.5,13.06L16.8,14.23L17.39,12.25L15.75,11L17.81,10.95L18.5,9L19.19,10.95L21.25,11M18.97,15.95C19.8,15.87 20.69,17.05 20.16,17.8C19.84,18.25 19.5,18.67 19.08,19.07C15.17,23 8.84,23 4.94,19.07C1.03,15.17 1.03,8.83 4.94,4.93C5.34,4.53 5.76,4.17 6.21,3.85C6.96,3.32 8.14,4.21 8.06,5.04C7.79,7.9 8.75,10.87 10.95,13.06C13.14,15.26 16.1,16.22 18.97,15.95M17.33,17.97C14.5,17.81 11.7,16.64 9.53,14.5C7.36,12.31 6.2,9.5 6.04,6.68C3.23,9.82 3.34,14.64 6.35,17.66C9.37,20.67 14.19,20.78 17.33,17.97Z" />
                </svg>
                </button>

                @* pumpkin *@

                @* Moon *@
    @* TODO: Update navbar - should we have a different one for our landing page than the dashboard? *@
                <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container-fluid">
                            <a class="navbar-brand" asp-area="" asp-controller="#" asp-action="#">Project Name</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Dashboard">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Events">Events</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Share">Share</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Connect">Connect</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div>
                            <button class="btn btn-dark"><a asp-controller="Users" asp-action="Logout">Logout</a></button>
                        </div>
                    </nav>
                </header>
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>

                <footer class="border-top footer text-muted">
                    <div class="container" >
                        &copy; 2022 - csharp_proj - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </div>
                </footer>
                <script src="~/lib/jquery/dist/jquery.min.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
                <script src="~/js/site.js" asp-append-version="true"></script>
                @await RenderSectionAsync("Scripts", required: false)
            </div>
        </div>
    </div>
    <script>
        //setDarkMode
        if(localStorage.getItem('theme') == 'dark'){
            setDarkMode();

            if(document.getElementById('checkbox').checked){
                localStorage.setItem('checkbox', true)
            }
        }
            function setDarkMode(){
                let isDark = document.body.classList.toggle('darkmode');
                if(isDark){
                    setDarkMode.checked = true;
                    localStorage.setItem('theme', 'dark')
                    document.getElementById('checkbox').setAttribute('checked', 'checked');

                }else{
                    setDarkMode.checked = true;
                    localStorage.removeItem('theme', 'dark');
                }
            }

    </script>
</body>
</html>

csharp_proj/Views/Shared/_Listings.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model Listing;


<div class="container text-center px-2">
    <h1 class="display-4"></h1>
    <div class="mt-5">
        <hr width="100%"/><br/>
        <table class="card bg-light">
            <thead>
                <tr class="d-flex justify-content-around">
                    <td class="w-33">Listings</td>
                </tr>
            </thead>
            @* @foreach(Listing Listing in ViewBag.Wed){ *@
                @* bool Commented = Listing.ListingCommented.Any(g => g.ListingId == Context.Session.GetInt32("UUID")); *@
@*
                <tr class="d-flex justify-content-around">
                    <td class="w-25"><a asp-action="One" asp-controller="Listings" asp-route-ListingId="@Listing.ListingId">@Listing.Title</a></td>
                    <td class="bg-secondary w-25">@Listing.Description</td>
                    <td class="bg-secondary w-25">@Listing.Price</td> *@
                    @* Maybe include a date for the post???When the concert will occur? *@
                    @* <td class="bg-secondary w-25">@Listing.CreatedAt</td> *@
                    @* <td class="w-25">@Listing.ListingCommented.Count()</td> *@


                    @* @if(Context.Session.GetInt32("UUID") == Listing.ListingId){
                        <td class="bg-secondary w-25"><a asp-action="DeleteListing" asp-controller="Listings" asp-route-ListingId="@Listing.ListingId">Delete</a></td>
                    } *@
                    @* <form asp-action="Comment" asp-controller="Listings" asp-route-ListingId="@Listing.ListingId" method="post">
                        @if(Context.Session.GetInt32("UUID") != Listing.ListingId){
                            @if(!Commented){
                                <td class="bg-secondary w-25"><button type="submit" class="btn-link">Comment</button></td>
                            }
                        }
                    </form> *@
                </tr>
            }
        </table>

    </div>
</div>

csharp_proj/Views/Shared/_Posts.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model Post;


<div class="container text-center px-2">
    <h1 class="display-4"></h1>
    <div class="mt-5">
        <hr width="100%"/><br/>
        <table class="card bg-light">
            <thead>
                <tr class="d-flex justify-content-around">
                    <td class="w-33">Posts</td>
                </tr>
            </thead>
            @* @foreach(Post Post in ViewBag.Events){ *@
                @* bool Commented = Post.PostCommented.Any(g => g.PostId == Context.Session.GetInt32("UUID")); *@

                @* <tr class="d-flex justify-content-around"> *@
                    @* <td class="w-25"><a asp-action="One" asp-controller="Posts" asp-route-PostId="@Post.PostId">@Post.Subject</a></td>
                    <td class="bg-secondary w-25">@Post.Message</td>
                    <td class="bg-secondary w-25">@Post.Comments</td> *@
                    @* Maybe include a date for the post???When the concert will occur? *@
                    @* <td class="bg-secondary w-25">@Post.CreatedAt</td>
                    <td class="w-25">@Post.PostCommented.Count()</td> *@
                    @* @if(Context.Session.GetInt32("UUID") == Post.PostId){
                        <td class="bg-secondary w-25"><a asp-action="DeletePost" asp-controller="Posts" asp-route-PostId="@Post.PostId">Delete</a></td>
                    } *@
                    @* <form asp-action="Comment" asp-controller="Posts" asp-route-PostId="@Post.PostId" method="post">
                        @if(Context.Session.GetInt32("UUID") != Post.PostId){
                            @if(!Commented){
                                <td class="bg-secondary w-25"><button type="submit" class="btn-link">Comment</button></td>
                            }
                        }
                    </form> *@
                </tr>
            @* } *@
        </table>

    </div>
</div>

csharp_proj/Views/Shared/_Reviews.cshtml
@{
    ViewData["Rating"] = "Home Page";
}
@model Review;


<div class="container text-center px-2">
    <h1 class="display-4"></h1>
    <div class="mt-5">
        <hr width="100%"/><br/>
        <table class="card bg-light">
            <thead>
                <tr class="d-flex justify-content-around">
                    <td class="w-33">Reviews</td>
                </tr>
            </thead>
            @* @foreach(Review Review in ViewBag.Wed){ *@
                @* bool Commented = Review.ReviewCommented.Any(g => g.ReviewId == Context.Session.GetInt32("UUID")); *@

                @* <tr class="d-flex justify-content-around">
                    <td class="w-25"><a asp-action="One" asp-controller="Reviews" asp-route-ReviewId="@Review.ReviewId">@Review.Rating</a></td>
                    <td class="bg-secondary w-25">@Review.Description</td> *@
                    @* Maybe include a date for the post???When the concert will occur? *@
                    @* <td class="bg-secondary w-25">@Review.CreatedAt</td> *@
                    @* <td class="w-25">@Review.ReviewCommented.Count()</td> *@


                    @* @if(Context.Session.GetInt32("UUID") == Review.ReviewId){
                        <td class="bg-secondary w-25"><a asp-action="DeleteReview" asp-controller="Reviews" asp-route-ReviewId="@Review.ReviewId">Delete</a></td>
                    } *@
                    @* <form asp-action="Comment" asp-controller="Reviews" asp-route-ReviewId="@Review.ReviewId" method="post">
                        @if(Context.Session.GetInt32("UUID") != Review.ReviewId){
                            @if(!Commented){
                                <td class="bg-secondary w-25"><button type="submit" class="btn-link">Comment</button></td>
                            }
                        }
                    </form> *@
                @* </tr> *@
            }
        </table>

    </div>
</div>